# Generated by Django 3.1.6 on 2021-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='test_fld',
            field=models.BooleanField(default=False),
        ),
    ]
