# Generated by Django 3.1.6 on 2021-04-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hero_test_fld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
