# Generated by Django 3.2 on 2021-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='link_list',
            new_name='link1',
        ),
        migrations.AddField(
            model_name='redirect',
            name='link10',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link2',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link3',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link4',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link5',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link6',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link7',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link8',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='link9',
            field=models.CharField(
                default=None, max_length=10485700, null=True),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
