# Generated by Django 3.1.8 on 2021-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_redirectlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redirectlink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
