# Generated by Django 3.1.8 on 2021-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0004_auto_20210430_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectlink',
            name='url2',
            field=models.CharField(max_length=10485700, null=True),
        ),
    ]
