# Generated by Django 3.1.7 on 2021-03-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_balance',
            field=models.IntegerField(default=100),
        ),
    ]
