# Generated by Django 3.2 on 2021-04-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210422_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_list',
            field=models.CharField(default=None, max_length=10485700, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='no_of_friends',
            field=models.IntegerField(default=0),
        ),
    ]
