# Generated by Django 3.1.8 on 2021-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210430_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='warned_email',
            field=models.BooleanField(default=False),
        ),
    ]
