# Generated by Django 3.1.8 on 2021-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_user_warned_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
