# Generated by Django 3.1.6 on 2021-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_discord_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_account',
            name='discord_id',
            field=models.IntegerField(default=None),
        ),
    ]
