# Generated by Django 3.1.8 on 2021-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20210512_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_account',
            name='discord_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_balance',
            field=models.BigIntegerField(default=100),
        ),
    ]
