# Generated by Django 3.1.6 on 2021-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_discord_account_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_account',
            name='bot_key',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
