# Generated by Django 3.1.8 on 2021-05-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20210512_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=100),
        ),
    ]
