# Generated by Django 3.1.6 on 2021-04-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_discord_account_bot_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_account',
            name='discord_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
