# Generated by Django 3.1.6 on 2021-04-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20210402_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discord_account',
            name='bot_key',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discord_account',
            name='discord_username',
            field=models.CharField(default=None, max_length=37),
        ),
    ]
