# Generated by Django 3.1.6 on 2021-04-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20210402_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord_account',
            name='bot_key',
        ),
    ]
