# Generated by Django 3.1.6 on 2021-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_discord_account_bot_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(editable=True),
        ),
    ]
