# Generated by Django 3.1.6 on 2021-04-14 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20210413_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transaction_list',
            field=models.CharField(default=None, max_length=100000000, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=100)),
                ('type', models.CharField(choices=[('add', 'add'), ('withdraw', 'withdraw')], max_length=10)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
    ]
