# Generated by Django 3.1.8 on 2021-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20210414_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_list',
            field=models.CharField(default=None, max_length=10485760, null=True),
        ),
    ]
