# Generated by Django 3.1.8 on 2021-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20210417_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transaction_list',
            field=models.CharField(default=None, max_length=10485700, null=True),
        ),
    ]
