# Generated by Django 3.1.8 on 2021-05-01 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0005_user_warned_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(
                    default=uuid.uuid4, editable=False, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('mail', models.EmailField(max_length=254)),
                ('djank_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
    ]
