# Generated by Django 3.1.8 on 2021-05-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='djank_user',
            new_name='user',
        ),
    ]
