# Generated by Django 3.1.8 on 2021-05-02 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20210501_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='unique_id_2',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
