# Generated by Django 3.1.8 on 2021-05-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_user_email_is_verified'),
        ('mail', '0003_query_unique_id_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user', unique=True),
        ),
    ]
