# Generated by Django 5.1 on 2024-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20210512_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
